services:
  frontend:
    build:
      context: .
      target: nginx-builder
    ports:
      - "8080:80"
    networks:
      - app-network

  backend-ws:
    build:
      context: .
      target: service-builder
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
